config/routes.rb
Rails.application.routes.draw do
  
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def new
      
    end
    
    def create
        params.permit!
       @article = Article.new(params[:article])
       
       @article.save()
       redirect_to @article
    end
    def index
        @articles = Article.all
    end
    def show
      @article = Article.find(params[:id]) 
      # test comment
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
    <tr>
        
        <th>Title</th>
        <th>Text</th>
        
    </tr>
    
    <% @articles.each do |article| %>
    <tr>
        
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        
    </tr>
    
    <% end %>
    
</table>

<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<h1> New Article<h1>
     <%= form_for :article, url: '/articles/' do |f| %>
        <p style="font-size:16px">
            <%= f.label :title %><br>
            <%= f.text_field :title %>
        </p>
    
        <p>
            <%= f.label :content %><br>
            <%= f.text_field :content %>
        </p>
    
        <p>
            <%= f.submit %>
        </p>
    
   <% end %>

app/views/articles/show.html.erb
<p>
    <strong> Title: </strong>
    <%= @article.title %>
</p>

<p>
    <Strong> Content: </strong>
    <%= @article.content %>
</p>

<%= link_to "Articles List", articles_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>